// flow-typed signature: 74bd1cad41aee9971d196b389bf5c4d2
// flow-typed version: <<STUB>>/@0xproject/subproviders_v^0.9.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@0xproject/subproviders'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@0xproject/subproviders' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@0xproject/subproviders/lib/src/index' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/src/subproviders/base_wallet_subprovider' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/src/subproviders/empty_wallet_subprovider' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/src/subproviders/fake_gas_estimate_subprovider' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/src/subproviders/ganache' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/src/subproviders/injected_web3' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/src/subproviders/ledger' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/src/subproviders/mnemonic_wallet' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/src/subproviders/nonce_tracker' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/src/subproviders/private_key_wallet' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/src/subproviders/redundant_subprovider' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/src/subproviders/subprovider' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/src/types' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/src/utils/wallet_utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@0xproject/subproviders/lib/src/index.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/src/index'>;
}
declare module '@0xproject/subproviders/lib/src/subproviders/base_wallet_subprovider.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/src/subproviders/base_wallet_subprovider'>;
}
declare module '@0xproject/subproviders/lib/src/subproviders/empty_wallet_subprovider.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/src/subproviders/empty_wallet_subprovider'>;
}
declare module '@0xproject/subproviders/lib/src/subproviders/fake_gas_estimate_subprovider.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/src/subproviders/fake_gas_estimate_subprovider'>;
}
declare module '@0xproject/subproviders/lib/src/subproviders/ganache.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/src/subproviders/ganache'>;
}
declare module '@0xproject/subproviders/lib/src/subproviders/injected_web3.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/src/subproviders/injected_web3'>;
}
declare module '@0xproject/subproviders/lib/src/subproviders/ledger.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/src/subproviders/ledger'>;
}
declare module '@0xproject/subproviders/lib/src/subproviders/mnemonic_wallet.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/src/subproviders/mnemonic_wallet'>;
}
declare module '@0xproject/subproviders/lib/src/subproviders/nonce_tracker.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/src/subproviders/nonce_tracker'>;
}
declare module '@0xproject/subproviders/lib/src/subproviders/private_key_wallet.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/src/subproviders/private_key_wallet'>;
}
declare module '@0xproject/subproviders/lib/src/subproviders/redundant_subprovider.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/src/subproviders/redundant_subprovider'>;
}
declare module '@0xproject/subproviders/lib/src/subproviders/subprovider.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/src/subproviders/subprovider'>;
}
declare module '@0xproject/subproviders/lib/src/types.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/src/types'>;
}
declare module '@0xproject/subproviders/lib/src/utils/wallet_utils.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/src/utils/wallet_utils'>;
}
