// flow-typed signature: 5264c70aacefda7046786cb10921771b
// flow-typed version: <<STUB>>/@0xproject/web3-wrapper_v^0.6.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@0xproject/web3-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@0xproject/web3-wrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@0xproject/web3-wrapper/lib/src/index' {
  declare module.exports: any;
}

declare module '@0xproject/web3-wrapper/lib/src/monorepo_scripts/postpublish' {
  declare module.exports: any;
}

declare module '@0xproject/web3-wrapper/lib/src/monorepo_scripts/stage_docs' {
  declare module.exports: any;
}

declare module '@0xproject/web3-wrapper/lib/src/types' {
  declare module.exports: any;
}

declare module '@0xproject/web3-wrapper/lib/src/web3_wrapper' {
  declare module.exports: any;
}

declare module '@0xproject/web3-wrapper/lib/test/utils/chai_setup' {
  declare module.exports: any;
}

declare module '@0xproject/web3-wrapper/lib/test/web3_wrapper_test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@0xproject/web3-wrapper/lib/src/index.js' {
  declare module.exports: $Exports<'@0xproject/web3-wrapper/lib/src/index'>;
}
declare module '@0xproject/web3-wrapper/lib/src/monorepo_scripts/postpublish.js' {
  declare module.exports: $Exports<'@0xproject/web3-wrapper/lib/src/monorepo_scripts/postpublish'>;
}
declare module '@0xproject/web3-wrapper/lib/src/monorepo_scripts/stage_docs.js' {
  declare module.exports: $Exports<'@0xproject/web3-wrapper/lib/src/monorepo_scripts/stage_docs'>;
}
declare module '@0xproject/web3-wrapper/lib/src/types.js' {
  declare module.exports: $Exports<'@0xproject/web3-wrapper/lib/src/types'>;
}
declare module '@0xproject/web3-wrapper/lib/src/web3_wrapper.js' {
  declare module.exports: $Exports<'@0xproject/web3-wrapper/lib/src/web3_wrapper'>;
}
declare module '@0xproject/web3-wrapper/lib/test/utils/chai_setup.js' {
  declare module.exports: $Exports<'@0xproject/web3-wrapper/lib/test/utils/chai_setup'>;
}
declare module '@0xproject/web3-wrapper/lib/test/web3_wrapper_test.js' {
  declare module.exports: $Exports<'@0xproject/web3-wrapper/lib/test/web3_wrapper_test'>;
}
