// flow-typed signature: c019c411a4a46f7f4da7adfe509bc995
// flow-typed version: <<STUB>>/rc-input-number_v4.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-input-number'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-input-number' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-input-number/dist/rc-input-number' {
  declare module.exports: any;
}

declare module 'rc-input-number/dist/rc-input-number.min' {
  declare module.exports: any;
}

declare module 'rc-input-number/es/index' {
  declare module.exports: any;
}

declare module 'rc-input-number/es/InputHandler' {
  declare module.exports: any;
}

declare module 'rc-input-number/lib/index' {
  declare module.exports: any;
}

declare module 'rc-input-number/lib/InputHandler' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-input-number/dist/rc-input-number.js' {
  declare module.exports: $Exports<'rc-input-number/dist/rc-input-number'>;
}
declare module 'rc-input-number/dist/rc-input-number.min.js' {
  declare module.exports: $Exports<'rc-input-number/dist/rc-input-number.min'>;
}
declare module 'rc-input-number/es/index.js' {
  declare module.exports: $Exports<'rc-input-number/es/index'>;
}
declare module 'rc-input-number/es/InputHandler.js' {
  declare module.exports: $Exports<'rc-input-number/es/InputHandler'>;
}
declare module 'rc-input-number/lib/index.js' {
  declare module.exports: $Exports<'rc-input-number/lib/index'>;
}
declare module 'rc-input-number/lib/InputHandler.js' {
  declare module.exports: $Exports<'rc-input-number/lib/InputHandler'>;
}
