// flow-typed signature: c24759ee1ef5f0b5ab8212a4a1a3339a
// flow-typed version: <<STUB>>/react-joyride_v^1.11.4/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-joyride'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-joyride' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-joyride/es/Beacon' {
  declare module.exports: any;
}

declare module 'react-joyride/es/index' {
  declare module.exports: any;
}

declare module 'react-joyride/es/Tooltip' {
  declare module.exports: any;
}

declare module 'react-joyride/es/utils' {
  declare module.exports: any;
}

declare module 'react-joyride/lib/Beacon' {
  declare module.exports: any;
}

declare module 'react-joyride/lib/index' {
  declare module.exports: any;
}

declare module 'react-joyride/lib/Tooltip' {
  declare module.exports: any;
}

declare module 'react-joyride/lib/utils' {
  declare module.exports: any;
}

declare module 'react-joyride/src/scripts/Beacon' {
  declare module.exports: any;
}

declare module 'react-joyride/src/scripts/index' {
  declare module.exports: any;
}

declare module 'react-joyride/src/scripts/Tooltip' {
  declare module.exports: any;
}

declare module 'react-joyride/src/scripts/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-joyride/es/Beacon.js' {
  declare module.exports: $Exports<'react-joyride/es/Beacon'>;
}
declare module 'react-joyride/es/index.js' {
  declare module.exports: $Exports<'react-joyride/es/index'>;
}
declare module 'react-joyride/es/Tooltip.js' {
  declare module.exports: $Exports<'react-joyride/es/Tooltip'>;
}
declare module 'react-joyride/es/utils.js' {
  declare module.exports: $Exports<'react-joyride/es/utils'>;
}
declare module 'react-joyride/lib/Beacon.js' {
  declare module.exports: $Exports<'react-joyride/lib/Beacon'>;
}
declare module 'react-joyride/lib/index.js' {
  declare module.exports: $Exports<'react-joyride/lib/index'>;
}
declare module 'react-joyride/lib/Tooltip.js' {
  declare module.exports: $Exports<'react-joyride/lib/Tooltip'>;
}
declare module 'react-joyride/lib/utils.js' {
  declare module.exports: $Exports<'react-joyride/lib/utils'>;
}
declare module 'react-joyride/src/scripts/Beacon.jsx' {
  declare module.exports: $Exports<'react-joyride/src/scripts/Beacon'>;
}
declare module 'react-joyride/src/scripts/index.jsx' {
  declare module.exports: $Exports<'react-joyride/src/scripts/index'>;
}
declare module 'react-joyride/src/scripts/Tooltip.jsx' {
  declare module.exports: $Exports<'react-joyride/src/scripts/Tooltip'>;
}
declare module 'react-joyride/src/scripts/utils.js' {
  declare module.exports: $Exports<'react-joyride/src/scripts/utils'>;
}
