// flow-typed signature: ebdf52acb72147629b26df4a2240826f
// flow-typed version: <<STUB>>/script-loader_v^0.7.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'script-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'script-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'script-loader/addScript' {
  declare module.exports: any;
}

// Filename aliases
declare module 'script-loader/addScript.js' {
  declare module.exports: $Exports<'script-loader/addScript'>;
}
declare module 'script-loader/index' {
  declare module.exports: $Exports<'script-loader'>;
}
declare module 'script-loader/index.js' {
  declare module.exports: $Exports<'script-loader'>;
}
