// flow-typed signature: 7be85f91fde2c9f7a0c5cee0220aa4bc
// flow-typed version: <<STUB>>/snapguidist_v^2.1.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'snapguidist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'snapguidist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'snapguidist/lib/api' {
  declare module.exports: any;
}

declare module 'snapguidist/lib/components/Code' {
  declare module.exports: any;
}

declare module 'snapguidist/lib/components/Playground' {
  declare module.exports: any;
}

declare module 'snapguidist/lib/components/PlaygroundRenderer' {
  declare module.exports: any;
}

declare module 'snapguidist/lib/components/Preview' {
  declare module.exports: any;
}

declare module 'snapguidist/lib/components/Test' {
  declare module.exports: any;
}

declare module 'snapguidist/lib/core/configureServer' {
  declare module.exports: any;
}

declare module 'snapguidist/lib/core/snapshot' {
  declare module.exports: any;
}

declare module 'snapguidist/lib/core/updateWebpackConfig' {
  declare module.exports: any;
}

declare module 'snapguidist/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'snapguidist/lib/api.js' {
  declare module.exports: $Exports<'snapguidist/lib/api'>;
}
declare module 'snapguidist/lib/components/Code.js' {
  declare module.exports: $Exports<'snapguidist/lib/components/Code'>;
}
declare module 'snapguidist/lib/components/Playground.js' {
  declare module.exports: $Exports<'snapguidist/lib/components/Playground'>;
}
declare module 'snapguidist/lib/components/PlaygroundRenderer.js' {
  declare module.exports: $Exports<'snapguidist/lib/components/PlaygroundRenderer'>;
}
declare module 'snapguidist/lib/components/Preview.js' {
  declare module.exports: $Exports<'snapguidist/lib/components/Preview'>;
}
declare module 'snapguidist/lib/components/Test.js' {
  declare module.exports: $Exports<'snapguidist/lib/components/Test'>;
}
declare module 'snapguidist/lib/core/configureServer.js' {
  declare module.exports: $Exports<'snapguidist/lib/core/configureServer'>;
}
declare module 'snapguidist/lib/core/snapshot.js' {
  declare module.exports: $Exports<'snapguidist/lib/core/snapshot'>;
}
declare module 'snapguidist/lib/core/updateWebpackConfig.js' {
  declare module.exports: $Exports<'snapguidist/lib/core/updateWebpackConfig'>;
}
declare module 'snapguidist/lib/index.js' {
  declare module.exports: $Exports<'snapguidist/lib/index'>;
}
