// flow-typed signature: a965a9b481d70ffe2bf2258dbc7b5c8f
// flow-typed version: <<STUB>>/webpack-s3-plugin_v1.0.0-rc.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-s3-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-s3-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-s3-plugin/dist/s3_plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-s3-plugin/dist/s3_plugin.js' {
  declare module.exports: $Exports<'webpack-s3-plugin/dist/s3_plugin'>;
}
