// flow-typed signature: c831c06cb4d1ad219c640b22e9580aaf
// flow-typed version: <<STUB>>/0x.js_v0.38.3/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '0x.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '0x.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '0x.js/lib/src/0x' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/contract_wrappers/generated/dummy_token' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/contract_wrappers/generated/ether_token' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/contract_wrappers/generated/exchange' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/contract_wrappers/generated/token_registry' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/contract_wrappers/generated/token_transfer_proxy' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/contract_wrappers/generated/token' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/index' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/schemas/zero_ex_config_schema' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/schemas/zero_ex_private_network_config_schema' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/schemas/zero_ex_public_network_config_schema' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/types' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/utils/constants' {
  declare module.exports: any;
}

// Filename aliases
declare module '0x.js/lib/src/0x.js' {
  declare module.exports: $Exports<'0x.js/lib/src/0x'>;
}
declare module '0x.js/lib/src/contract_wrappers/generated/dummy_token.js' {
  declare module.exports: $Exports<'0x.js/lib/src/contract_wrappers/generated/dummy_token'>;
}
declare module '0x.js/lib/src/contract_wrappers/generated/ether_token.js' {
  declare module.exports: $Exports<'0x.js/lib/src/contract_wrappers/generated/ether_token'>;
}
declare module '0x.js/lib/src/contract_wrappers/generated/exchange.js' {
  declare module.exports: $Exports<'0x.js/lib/src/contract_wrappers/generated/exchange'>;
}
declare module '0x.js/lib/src/contract_wrappers/generated/token_registry.js' {
  declare module.exports: $Exports<'0x.js/lib/src/contract_wrappers/generated/token_registry'>;
}
declare module '0x.js/lib/src/contract_wrappers/generated/token_transfer_proxy.js' {
  declare module.exports: $Exports<'0x.js/lib/src/contract_wrappers/generated/token_transfer_proxy'>;
}
declare module '0x.js/lib/src/contract_wrappers/generated/token.js' {
  declare module.exports: $Exports<'0x.js/lib/src/contract_wrappers/generated/token'>;
}
declare module '0x.js/lib/src/index.js' {
  declare module.exports: $Exports<'0x.js/lib/src/index'>;
}
declare module '0x.js/lib/src/schemas/zero_ex_config_schema.js' {
  declare module.exports: $Exports<'0x.js/lib/src/schemas/zero_ex_config_schema'>;
}
declare module '0x.js/lib/src/schemas/zero_ex_private_network_config_schema.js' {
  declare module.exports: $Exports<'0x.js/lib/src/schemas/zero_ex_private_network_config_schema'>;
}
declare module '0x.js/lib/src/schemas/zero_ex_public_network_config_schema.js' {
  declare module.exports: $Exports<'0x.js/lib/src/schemas/zero_ex_public_network_config_schema'>;
}
declare module '0x.js/lib/src/types.js' {
  declare module.exports: $Exports<'0x.js/lib/src/types'>;
}
declare module '0x.js/lib/src/utils/constants.js' {
  declare module.exports: $Exports<'0x.js/lib/src/utils/constants'>;
}
