// flow-typed signature: 5409b83635080cba667975561457fded
// flow-typed version: <<STUB>>/0x.js_v^0.33.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '0x.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '0x.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '0x.js/lib/src/0x' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/artifacts' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/contract_wrappers/contract_wrapper' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/contract_wrappers/ether_token_wrapper' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/contract_wrappers/exchange_wrapper' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/contract_wrappers/generated/dummy_token' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/contract_wrappers/generated/ether_token' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/contract_wrappers/generated/exchange' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/contract_wrappers/generated/token_registry' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/contract_wrappers/generated/token_transfer_proxy' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/contract_wrappers/generated/token' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/contract_wrappers/token_registry_wrapper' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/contract_wrappers/token_transfer_proxy_wrapper' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/contract_wrappers/token_wrapper' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/index' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/order_watcher/event_watcher' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/order_watcher/expiration_watcher' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/order_watcher/order_state_watcher' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/order_watcher/remaining_fillable_calculator' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/schemas/zero_ex_config_schema' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/schemas/zero_ex_private_network_config_schema' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/schemas/zero_ex_public_network_config_schema' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/stores/balance_proxy_allowance_lazy_store' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/stores/order_filled_cancelled_lazy_store' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/types' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/utils/assert' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/utils/constants' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/utils/decorators' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/utils/exchange_transfer_simulator' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/utils/filter_utils' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/utils/order_state_utils' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/utils/order_validation_utils' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/utils/signature_utils' {
  declare module.exports: any;
}

declare module '0x.js/lib/src/utils/utils' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/0x.js_test' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/artifacts_test' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/assert_test' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/ether_token_wrapper_test' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/event_watcher_test' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/exchange_transfer_simulator_test' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/exchange_wrapper_test' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/expiration_watcher_test' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/order_state_watcher_test' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/order_validation_test' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/remaining_fillable_calculator_test' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/subscription_test' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/token_registry_wrapper_test' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/token_transfer_proxy_wrapper_test' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/token_wrapper_test' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/utils/chai_setup' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/utils/constants' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/utils/fill_scenarios' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/utils/order_factory' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/utils/report_callback_errors' {
  declare module.exports: any;
}

declare module '0x.js/lib/test/utils/token_utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '0x.js/lib/src/0x.js' {
  declare module.exports: $Exports<'0x.js/lib/src/0x'>;
}
declare module '0x.js/lib/src/artifacts.js' {
  declare module.exports: $Exports<'0x.js/lib/src/artifacts'>;
}
declare module '0x.js/lib/src/contract_wrappers/contract_wrapper.js' {
  declare module.exports: $Exports<'0x.js/lib/src/contract_wrappers/contract_wrapper'>;
}
declare module '0x.js/lib/src/contract_wrappers/ether_token_wrapper.js' {
  declare module.exports: $Exports<'0x.js/lib/src/contract_wrappers/ether_token_wrapper'>;
}
declare module '0x.js/lib/src/contract_wrappers/exchange_wrapper.js' {
  declare module.exports: $Exports<'0x.js/lib/src/contract_wrappers/exchange_wrapper'>;
}
declare module '0x.js/lib/src/contract_wrappers/generated/dummy_token.js' {
  declare module.exports: $Exports<'0x.js/lib/src/contract_wrappers/generated/dummy_token'>;
}
declare module '0x.js/lib/src/contract_wrappers/generated/ether_token.js' {
  declare module.exports: $Exports<'0x.js/lib/src/contract_wrappers/generated/ether_token'>;
}
declare module '0x.js/lib/src/contract_wrappers/generated/exchange.js' {
  declare module.exports: $Exports<'0x.js/lib/src/contract_wrappers/generated/exchange'>;
}
declare module '0x.js/lib/src/contract_wrappers/generated/token_registry.js' {
  declare module.exports: $Exports<'0x.js/lib/src/contract_wrappers/generated/token_registry'>;
}
declare module '0x.js/lib/src/contract_wrappers/generated/token_transfer_proxy.js' {
  declare module.exports: $Exports<'0x.js/lib/src/contract_wrappers/generated/token_transfer_proxy'>;
}
declare module '0x.js/lib/src/contract_wrappers/generated/token.js' {
  declare module.exports: $Exports<'0x.js/lib/src/contract_wrappers/generated/token'>;
}
declare module '0x.js/lib/src/contract_wrappers/token_registry_wrapper.js' {
  declare module.exports: $Exports<'0x.js/lib/src/contract_wrappers/token_registry_wrapper'>;
}
declare module '0x.js/lib/src/contract_wrappers/token_transfer_proxy_wrapper.js' {
  declare module.exports: $Exports<'0x.js/lib/src/contract_wrappers/token_transfer_proxy_wrapper'>;
}
declare module '0x.js/lib/src/contract_wrappers/token_wrapper.js' {
  declare module.exports: $Exports<'0x.js/lib/src/contract_wrappers/token_wrapper'>;
}
declare module '0x.js/lib/src/index.js' {
  declare module.exports: $Exports<'0x.js/lib/src/index'>;
}
declare module '0x.js/lib/src/order_watcher/event_watcher.js' {
  declare module.exports: $Exports<'0x.js/lib/src/order_watcher/event_watcher'>;
}
declare module '0x.js/lib/src/order_watcher/expiration_watcher.js' {
  declare module.exports: $Exports<'0x.js/lib/src/order_watcher/expiration_watcher'>;
}
declare module '0x.js/lib/src/order_watcher/order_state_watcher.js' {
  declare module.exports: $Exports<'0x.js/lib/src/order_watcher/order_state_watcher'>;
}
declare module '0x.js/lib/src/order_watcher/remaining_fillable_calculator.js' {
  declare module.exports: $Exports<'0x.js/lib/src/order_watcher/remaining_fillable_calculator'>;
}
declare module '0x.js/lib/src/schemas/zero_ex_config_schema.js' {
  declare module.exports: $Exports<'0x.js/lib/src/schemas/zero_ex_config_schema'>;
}
declare module '0x.js/lib/src/schemas/zero_ex_private_network_config_schema.js' {
  declare module.exports: $Exports<'0x.js/lib/src/schemas/zero_ex_private_network_config_schema'>;
}
declare module '0x.js/lib/src/schemas/zero_ex_public_network_config_schema.js' {
  declare module.exports: $Exports<'0x.js/lib/src/schemas/zero_ex_public_network_config_schema'>;
}
declare module '0x.js/lib/src/stores/balance_proxy_allowance_lazy_store.js' {
  declare module.exports: $Exports<'0x.js/lib/src/stores/balance_proxy_allowance_lazy_store'>;
}
declare module '0x.js/lib/src/stores/order_filled_cancelled_lazy_store.js' {
  declare module.exports: $Exports<'0x.js/lib/src/stores/order_filled_cancelled_lazy_store'>;
}
declare module '0x.js/lib/src/types.js' {
  declare module.exports: $Exports<'0x.js/lib/src/types'>;
}
declare module '0x.js/lib/src/utils/assert.js' {
  declare module.exports: $Exports<'0x.js/lib/src/utils/assert'>;
}
declare module '0x.js/lib/src/utils/constants.js' {
  declare module.exports: $Exports<'0x.js/lib/src/utils/constants'>;
}
declare module '0x.js/lib/src/utils/decorators.js' {
  declare module.exports: $Exports<'0x.js/lib/src/utils/decorators'>;
}
declare module '0x.js/lib/src/utils/exchange_transfer_simulator.js' {
  declare module.exports: $Exports<'0x.js/lib/src/utils/exchange_transfer_simulator'>;
}
declare module '0x.js/lib/src/utils/filter_utils.js' {
  declare module.exports: $Exports<'0x.js/lib/src/utils/filter_utils'>;
}
declare module '0x.js/lib/src/utils/order_state_utils.js' {
  declare module.exports: $Exports<'0x.js/lib/src/utils/order_state_utils'>;
}
declare module '0x.js/lib/src/utils/order_validation_utils.js' {
  declare module.exports: $Exports<'0x.js/lib/src/utils/order_validation_utils'>;
}
declare module '0x.js/lib/src/utils/signature_utils.js' {
  declare module.exports: $Exports<'0x.js/lib/src/utils/signature_utils'>;
}
declare module '0x.js/lib/src/utils/utils.js' {
  declare module.exports: $Exports<'0x.js/lib/src/utils/utils'>;
}
declare module '0x.js/lib/test/0x.js_test.js' {
  declare module.exports: $Exports<'0x.js/lib/test/0x.js_test'>;
}
declare module '0x.js/lib/test/artifacts_test.js' {
  declare module.exports: $Exports<'0x.js/lib/test/artifacts_test'>;
}
declare module '0x.js/lib/test/assert_test.js' {
  declare module.exports: $Exports<'0x.js/lib/test/assert_test'>;
}
declare module '0x.js/lib/test/ether_token_wrapper_test.js' {
  declare module.exports: $Exports<'0x.js/lib/test/ether_token_wrapper_test'>;
}
declare module '0x.js/lib/test/event_watcher_test.js' {
  declare module.exports: $Exports<'0x.js/lib/test/event_watcher_test'>;
}
declare module '0x.js/lib/test/exchange_transfer_simulator_test.js' {
  declare module.exports: $Exports<'0x.js/lib/test/exchange_transfer_simulator_test'>;
}
declare module '0x.js/lib/test/exchange_wrapper_test.js' {
  declare module.exports: $Exports<'0x.js/lib/test/exchange_wrapper_test'>;
}
declare module '0x.js/lib/test/expiration_watcher_test.js' {
  declare module.exports: $Exports<'0x.js/lib/test/expiration_watcher_test'>;
}
declare module '0x.js/lib/test/order_state_watcher_test.js' {
  declare module.exports: $Exports<'0x.js/lib/test/order_state_watcher_test'>;
}
declare module '0x.js/lib/test/order_validation_test.js' {
  declare module.exports: $Exports<'0x.js/lib/test/order_validation_test'>;
}
declare module '0x.js/lib/test/remaining_fillable_calculator_test.js' {
  declare module.exports: $Exports<'0x.js/lib/test/remaining_fillable_calculator_test'>;
}
declare module '0x.js/lib/test/subscription_test.js' {
  declare module.exports: $Exports<'0x.js/lib/test/subscription_test'>;
}
declare module '0x.js/lib/test/token_registry_wrapper_test.js' {
  declare module.exports: $Exports<'0x.js/lib/test/token_registry_wrapper_test'>;
}
declare module '0x.js/lib/test/token_transfer_proxy_wrapper_test.js' {
  declare module.exports: $Exports<'0x.js/lib/test/token_transfer_proxy_wrapper_test'>;
}
declare module '0x.js/lib/test/token_wrapper_test.js' {
  declare module.exports: $Exports<'0x.js/lib/test/token_wrapper_test'>;
}
declare module '0x.js/lib/test/utils/chai_setup.js' {
  declare module.exports: $Exports<'0x.js/lib/test/utils/chai_setup'>;
}
declare module '0x.js/lib/test/utils/constants.js' {
  declare module.exports: $Exports<'0x.js/lib/test/utils/constants'>;
}
declare module '0x.js/lib/test/utils/fill_scenarios.js' {
  declare module.exports: $Exports<'0x.js/lib/test/utils/fill_scenarios'>;
}
declare module '0x.js/lib/test/utils/order_factory.js' {
  declare module.exports: $Exports<'0x.js/lib/test/utils/order_factory'>;
}
declare module '0x.js/lib/test/utils/report_callback_errors.js' {
  declare module.exports: $Exports<'0x.js/lib/test/utils/report_callback_errors'>;
}
declare module '0x.js/lib/test/utils/token_utils.js' {
  declare module.exports: $Exports<'0x.js/lib/test/utils/token_utils'>;
}
