// flow-typed signature: 1a202f1e67f60b4d9e85c4ccdf8426d1
// flow-typed version: <<STUB>>/bignumber_v^1.1.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bignumber'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bignumber' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bignumber/example' {
  declare module.exports: any;
}

declare module 'bignumber/lib/rsa/b64' {
  declare module.exports: any;
}

declare module 'bignumber/lib/rsa/index' {
  declare module.exports: any;
}

declare module 'bignumber/lib/rsa/jsbn' {
  declare module.exports: any;
}

declare module 'bignumber/lib/rsa/rng' {
  declare module.exports: any;
}

declare module 'bignumber/lib/rsa/rsa' {
  declare module.exports: any;
}

declare module 'bignumber/lib/rsa/sign' {
  declare module.exports: any;
}

declare module 'bignumber/original/base64' {
  declare module.exports: any;
}

declare module 'bignumber/original/jsbn' {
  declare module.exports: any;
}

declare module 'bignumber/original/jsbn2' {
  declare module.exports: any;
}

declare module 'bignumber/original/prng4' {
  declare module.exports: any;
}

declare module 'bignumber/original/rng' {
  declare module.exports: any;
}

declare module 'bignumber/original/rsa' {
  declare module.exports: any;
}

declare module 'bignumber/original/rsa2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bignumber/example.js' {
  declare module.exports: $Exports<'bignumber/example'>;
}
declare module 'bignumber/index' {
  declare module.exports: $Exports<'bignumber'>;
}
declare module 'bignumber/index.js' {
  declare module.exports: $Exports<'bignumber'>;
}
declare module 'bignumber/lib/rsa/b64.js' {
  declare module.exports: $Exports<'bignumber/lib/rsa/b64'>;
}
declare module 'bignumber/lib/rsa/index.js' {
  declare module.exports: $Exports<'bignumber/lib/rsa/index'>;
}
declare module 'bignumber/lib/rsa/jsbn.js' {
  declare module.exports: $Exports<'bignumber/lib/rsa/jsbn'>;
}
declare module 'bignumber/lib/rsa/rng.js' {
  declare module.exports: $Exports<'bignumber/lib/rsa/rng'>;
}
declare module 'bignumber/lib/rsa/rsa.js' {
  declare module.exports: $Exports<'bignumber/lib/rsa/rsa'>;
}
declare module 'bignumber/lib/rsa/sign.js' {
  declare module.exports: $Exports<'bignumber/lib/rsa/sign'>;
}
declare module 'bignumber/original/base64.js' {
  declare module.exports: $Exports<'bignumber/original/base64'>;
}
declare module 'bignumber/original/jsbn.js' {
  declare module.exports: $Exports<'bignumber/original/jsbn'>;
}
declare module 'bignumber/original/jsbn2.js' {
  declare module.exports: $Exports<'bignumber/original/jsbn2'>;
}
declare module 'bignumber/original/prng4.js' {
  declare module.exports: $Exports<'bignumber/original/prng4'>;
}
declare module 'bignumber/original/rng.js' {
  declare module.exports: $Exports<'bignumber/original/rng'>;
}
declare module 'bignumber/original/rsa.js' {
  declare module.exports: $Exports<'bignumber/original/rsa'>;
}
declare module 'bignumber/original/rsa2.js' {
  declare module.exports: $Exports<'bignumber/original/rsa2'>;
}
