// @flow

export const SET_CURRENT_TOKEN: 'ui/SET_CURRENT_TOKEN' = 'ui/SET_CURRENT_TOKEN';
export const SET_CURRENT_PAIR: 'ui/SET_CURRENT_PAIR' = 'ui/SET_CURRENT_PAIR';
export const SET_SEARCH_QUERY: 'ui/SET_SEARCH_QUERY' = 'ui/SET_SEARCH_QUERY';
export const SET_BALANCE_LOADING: 'ui/SET_BALANCE_LOADING' = 'ui/SET_BALANCE_LOADING';
export const FILL_FIELD: 'ui/FILL_FIELD' = 'ui/FILL_FIELD';
export const SEND_NOTIFICATION: 'ui/SEND_NOTIFICATION' = 'ui/SEND_NOTIFICATION';
