export const ETHEREUM_PROVIDER_SUCCESS = 'ETHEREUM_PROVIDER_SUCCESS';
export const FETCH_ASSET_PAIRS_REQUEST = 'FETCH_ASSET_PAIRS_REQUEST';
export const CHECK_PAIR_REQUEST = 'CHECK_PAIR_REQUEST';
export const CLEAR_ALL_REDUCERS = 'CLEAR_ALL_REDUCERS';
