export const ETHEREUM_PROVIDER_SUCCESS = 'ETHEREUM_PROVIDER_SUCCESS';
export const FETCH_ASSET_PAIRS_REQUEST = 'FETCH_ASSET_PAIRS_REQUEST';
export const CHECK_PAIR_REQUEST = 'CHECK_PAIR_REQUEST';
export const CLEAR_ALL_REDUCERS = 'CLEAR_ALL_REDUCERS';
export const SET_WALLET_STATE = 'wallet/SET_WALLET_STATE';
export const SEND_SOCKET_MESSAGE = 'SEND_SOCKET_MESSAGE';
export const SET_APPROVAL_REQUEST = 'assets/SET_APPROVAL_REQUEST';
export const DEPOSIT_WITHDRAW_REQUEST = 'assets/DEPOSIT_WITHDRAW_REQUEST';

export const SUBSCRIBE_CHART_ON_ORDER_UPDATE = 'orders/SUBSCRIBE_CHART_ON_ORDER_UPDATE';

export const TRADING_CHART_INITIALIZE_SUBSCRIBE = 'trading-chart/INITIALIZE_SUBSCRIBE';
export const TRADING_CHART_SUBSCRIBE_ON_ORDER_CREATE = 'trading-chart/SUBSCRIBE_ON_ORDER_CREATE';
export const POST_ORDER_REQUEST = 'orders/POST_ORDER_REQUEST';
