// flow-typed signature: 98e131f86951300297657d028eae2bb4
// flow-typed version: <<STUB>>/@0xproject/subproviders_v^0.3.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@0xproject/subproviders'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@0xproject/subproviders' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@0xproject/subproviders/lib/src/index' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/src/subproviders/injected_web3' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/src/subproviders/ledger' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/src/subproviders/redundant_rpc' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/src/subproviders/subprovider' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/src/types' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/test/chai_setup' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/test/integration/ledger_subprovider_test' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/test/unit/ledger_subprovider_test' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/test/unit/redundant_rpc_subprovider_test' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/lib/test/utils/report_callback_errors' {
  declare module.exports: any;
}

declare module '@0xproject/subproviders/scripts/postpublish' {
  declare module.exports: any;
}

// Filename aliases
declare module '@0xproject/subproviders/lib/src/index.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/src/index'>;
}
declare module '@0xproject/subproviders/lib/src/subproviders/injected_web3.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/src/subproviders/injected_web3'>;
}
declare module '@0xproject/subproviders/lib/src/subproviders/ledger.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/src/subproviders/ledger'>;
}
declare module '@0xproject/subproviders/lib/src/subproviders/redundant_rpc.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/src/subproviders/redundant_rpc'>;
}
declare module '@0xproject/subproviders/lib/src/subproviders/subprovider.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/src/subproviders/subprovider'>;
}
declare module '@0xproject/subproviders/lib/src/types.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/src/types'>;
}
declare module '@0xproject/subproviders/lib/test/chai_setup.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/test/chai_setup'>;
}
declare module '@0xproject/subproviders/lib/test/integration/ledger_subprovider_test.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/test/integration/ledger_subprovider_test'>;
}
declare module '@0xproject/subproviders/lib/test/unit/ledger_subprovider_test.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/test/unit/ledger_subprovider_test'>;
}
declare module '@0xproject/subproviders/lib/test/unit/redundant_rpc_subprovider_test.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/test/unit/redundant_rpc_subprovider_test'>;
}
declare module '@0xproject/subproviders/lib/test/utils/report_callback_errors.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/lib/test/utils/report_callback_errors'>;
}
declare module '@0xproject/subproviders/scripts/postpublish.js' {
  declare module.exports: $Exports<'@0xproject/subproviders/scripts/postpublish'>;
}
