// flow-typed signature: 06a9e68bc32f14bd7d8863ae3d988400
// flow-typed version: <<STUB>>/human-standard-token-abi_v1.0.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'human-standard-token-abi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'human-standard-token-abi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'human-standard-token-abi/example/bundle' {
  declare module.exports: any;
}

declare module 'human-standard-token-abi/example/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'human-standard-token-abi/example/bundle.js' {
  declare module.exports: $Exports<'human-standard-token-abi/example/bundle'>;
}
declare module 'human-standard-token-abi/example/index.js' {
  declare module.exports: $Exports<'human-standard-token-abi/example/index'>;
}
declare module 'human-standard-token-abi/index' {
  declare module.exports: $Exports<'human-standard-token-abi'>;
}
declare module 'human-standard-token-abi/index.js' {
  declare module.exports: $Exports<'human-standard-token-abi'>;
}
